In [1]:
from pathlib import Path
from scipy import stats

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns

np.set_printoptions(suppress=True)

pd.options.display.max_columns = None
pd.options.display.max_rows = None
pd.options.display.max_colwidth = None

from sklearn.linear_model import LogisticRegression

from IPython.display import display, Markdown

import json

In [2]:
path1 = Path(r"A:\Workspace\Python\Masterarbeit\Kaggle Home Credit Datensatz")
path2 = Path(r"C:\Users\rober\Documents\Workspace\Python\Masterarbeit\Kaggle Home Credit Datensatz")

if path1.is_dir():
    DATASET_DIR = path1
else:
    DATASET_DIR = path2

In [3]:
MODEL_APPLICATION = "1.1. Esembler_Logistic_application.json"
MODEL_BUREAU = "1.2. Esembler_Logistic_bureau.json"
MODEL_PA_POS = "1.3. Esembler_Logistic_pa_pos.json"
MODEL_PA_IP = "1.4. Esembler_Logistic_pa_ip.json"
MODEL_PA_CC = "1.5. Esembler_Logistic_pa_cc.json"

In [4]:
with open(DATASET_DIR / "Models" / MODEL_APPLICATION, 'r') as file:
    application_log = json.load(file)
    
with open(DATASET_DIR / "Models" / MODEL_BUREAU, 'r') as file:
    bureau_log = json.load(file)
    
with open(DATASET_DIR / "Models" / MODEL_PA_POS, 'r') as file:
    pa_pos_log = json.load(file)
    
with open(DATASET_DIR / "Models" / MODEL_PA_IP, 'r') as file:
    pa_ip_log = json.load(file)
    
with open(DATASET_DIR / "Models" / MODEL_PA_CC, 'r') as file:
    pa_cc_log = json.load(file)

LOG_LIST = [application_log, bureau_log, pa_pos_log, pa_ip_log, pa_cc_log]

In [5]:
MODEL_APPLICATION = "2.1. Esembler_DecisionTree_Application.json"
MODEL_BUREAU = "2.2. Esembler_DecisionTree_bureau.json"
MODEL_PA_POS = "2.3. Esembler_DecisionTree_pa_pos.json"
MODEL_PA_IP = "2.4. Esembler_DecisionTree_pa_ip.json"
MODEL_PA_CC = "2.5. Esembler_DecisionTree_pa_cc.json"

In [6]:
with open(DATASET_DIR / "Models" / MODEL_APPLICATION, 'r') as file:
    application_dt = json.load(file)
    
with open(DATASET_DIR / "Models" / MODEL_BUREAU, 'r') as file:
    bureau_dt = json.load(file)
    
with open(DATASET_DIR / "Models" / MODEL_PA_POS, 'r') as file:
    pa_pos_dt = json.load(file)
    
with open(DATASET_DIR / "Models" / MODEL_PA_IP, 'r') as file:
    pa_ip_dt = json.load(file)
    
with open(DATASET_DIR / "Models" / MODEL_PA_CC, 'r') as file:
    pa_cc_dt = json.load(file)

DT_LIST = [application_dt, bureau_dt, pa_pos_dt, pa_ip_dt, pa_cc_dt]

In [7]:
MODEL_APPLICATION = "3.1. Esembler_RandomForest_Application.json"
MODEL_BUREAU = "3.2. Esembler_RandomForest_bureau.json"
MODEL_PA_POS = "3.3. Esembler_RandomForest_pa_pos.json"
MODEL_PA_IP = "3.4. Esembler_RandomForest_pa_ip.json"
MODEL_PA_CC = "3.5. Esembler_RandomForest_pa_cc.json"

In [8]:
with open(DATASET_DIR / "Models" / MODEL_APPLICATION, 'r') as file:
    application_rf = json.load(file)
    
with open(DATASET_DIR / "Models" / MODEL_BUREAU, 'r') as file:
    bureau_rf = json.load(file)
    
with open(DATASET_DIR / "Models" / MODEL_PA_POS, 'r') as file:
    pa_pos_rf = json.load(file)
    
with open(DATASET_DIR / "Models" / MODEL_PA_IP, 'r') as file:
    pa_ip_rf = json.load(file)
    
with open(DATASET_DIR / "Models" / MODEL_PA_CC, 'r') as file:
    pa_cc_rf = json.load(file)

RF_LIST = [application_rf, bureau_rf, pa_pos_rf, pa_ip_rf, pa_cc_rf]

# Anzahl Parameter

In [30]:
df = pd.DataFrame({"Datensatz":["Application", "Bureau", "PA_POS", "PA_IP", "PA_CC"]})
df = df.set_index("Datensatz")
df["# Parameter"] = [len(x["keep"]) + len(x["drop"]) for x in LOG_LIST]

df["# Parameter log. R."] = [len(x["keep"]) for x in LOG_LIST]
df["AUC log. R."] = [round(x["auc"][-1],4) for x in LOG_LIST]
df["# Parameter DT"] = [len(x["keep"]) for x in DT_LIST]
df["AUC DT"] = [round(x["auc"][-1],4) for x in DT_LIST]
df["# Parameter RF"] = [len(x["keep"]) for x in RF_LIST]
df["AUC RF"] = [round(x["auc"][-1],4) for x in RF_LIST]

df.loc["SUM"] = [df["# Parameter"].sum(), df["# Parameter log. R."].sum(), "-", df["# Parameter DT"].sum(), "-", df["# Parameter RF"].sum(), "-"]
df

,# Parameter,# Parameter log. R.,AUC log. R.,# Parameter DT,AUC DT,# Parameter RF,AUC RF
Datensatz,,,,,,,
Application,35,29,0.7868,12,0.8007,10,0.8131
Bureau,9,6,0.5926,6,0.5996,7,0.6125
PA_POS,21,20,0.6354,12,0.6168,17,0.6361
PA_IP,37,24,0.6294,16,0.6075,27,0.6362
PA_CC,35,22,0.6224,14,0.6346,21,0.6509
SUM,137,101,-,60,-,82,-

# Application

In [49]:
log = application_log
dt = application_dt
rf = application_rf

In [50]:
df = pd.DataFrame()
df = pd.concat([df,pd.DataFrame({"logistische Regression":log["keep"]})],axis=1)
df = pd.concat([df,pd.DataFrame({"AUC log. R.": [round(x,4) for x in log["auc"]]})],axis=1)
df = pd.concat([df,pd.DataFrame({"Entscheidungsbaum":dt["keep"]})],axis=1)
df = pd.concat([df,pd.DataFrame({"AUC DT": [round(x,4) for x in dt["auc"]]})],axis=1)
df = pd.concat([df,pd.DataFrame({"Random Forest":rf["keep"]})],axis=1)
df = pd.concat([df,pd.DataFrame({"AUC RF": [round(x,4) for x in rf["auc"]]})],axis=1)
df[0:10]

,logistische Regression,AUC log. R.,Entscheidungsbaum,AUC DT,Random Forest,AUC RF
0,A_EXT_SOURCE_1,0.6978,A_EXT_SOURCE_3,0.7088,A_EXT_SOURCE_3,0.7155
1,A_DAYS_BIRTH,0.7277,A_AMT_REQ_CREDIT_BUREAU_DAY,0.7338,A_EXT_SOURCE_1,0.7649
2,A_EXT_SOURCE_3,0.7614,A_DAYS_BIRTH,0.7547,A_EXT_SOURCE_2,0.7778
3,A_LANDAREA_AVG,0.7681,A_EXT_SOURCE_1,0.7966,A_AMT_REQ_CREDIT_BUREAU_DAY,0.7983
4,A_EXT_SOURCE_2,0.7778,A_EXT_SOURCE_2,0.7993,A_AMT_REQ_CREDIT_BUREAU_HOUR,0.7985
5,A_TOTALAREA_MODE,0.7791,A_AMT_REQ_CREDIT_BUREAU_QRT,0.7998,A_YEARS_BEGINEXPLUATATION_AVG,0.7998
6,A_AMT_CREDIT,0.7795,A_AMT_REQ_CREDIT_BUREAU_WEEK,0.7999,A_DAYS_EMPLOYED,0.8003
7,A_AMT_ANNUITY,0.7800,A_BASEMENTAREA_AVG,0.8000,A_DAYS_BIRTH,0.8080
8,A_CREDIT/INCOME,0.7811,A_LANDAREA_AVG,0.8005,A_BASEMENTAREA_AVG,0.8126
9,A_CODE_GENDER,0.7831,A_AMT_ANNUITY,0.8006,A_LANDAREA_AVG,0.8131

In [51]:
df

,logistische Regression,AUC log. R.,Entscheidungsbaum,AUC DT,Random Forest,AUC RF
0,A_EXT_SOURCE_1,0.6978,A_EXT_SOURCE_3,0.7088,A_EXT_SOURCE_3,0.7155
1,A_DAYS_BIRTH,0.7277,A_AMT_REQ_CREDIT_BUREAU_DAY,0.7338,A_EXT_SOURCE_1,0.7649
2,A_EXT_SOURCE_3,0.7614,A_DAYS_BIRTH,0.7547,A_EXT_SOURCE_2,0.7778
3,A_LANDAREA_AVG,0.7681,A_EXT_SOURCE_1,0.7966,A_AMT_REQ_CREDIT_BUREAU_DAY,0.7983
4,A_EXT_SOURCE_2,0.7778,A_EXT_SOURCE_2,0.7993,A_AMT_REQ_CREDIT_BUREAU_HOUR,0.7985
5,A_TOTALAREA_MODE,0.7791,A_AMT_REQ_CREDIT_BUREAU_QRT,0.7998,A_YEARS_BEGINEXPLUATATION_AVG,0.7998
6,A_AMT_CREDIT,0.7795,A_AMT_REQ_CREDIT_BUREAU_WEEK,0.7999,A_DAYS_EMPLOYED,0.8003
7,A_AMT_ANNUITY,0.7800,A_BASEMENTAREA_AVG,0.8000,A_DAYS_BIRTH,0.8080
8,A_CREDIT/INCOME,0.7811,A_LANDAREA_AVG,0.8005,A_BASEMENTAREA_AVG,0.8126
9,A_CODE_GENDER,0.7831,A_AMT_ANNUITY,0.8006,A_LANDAREA_AVG,0.8131
10,A_DAYS_EMPLOYED,0.7839,A_AMT_INCOME_TOTAL,0.8007,NaN,NaN
11,A_FLAG_DOCUMENT_3,0.7847,A_ORGANIZATION_TYPE,0.8007,NaN,NaN
12,A_REGION_POPULATION_RELATIVE,0.7853,NaN,NaN,NaN,NaN
13,A_BASEMENTAREA_AVG,0.7854,NaN,NaN,NaN,NaN
14,A_REGION_RATING_CLIENT,0.7855,NaN,NaN,NaN,NaN
15,A_YEARS_BEGINEXPLUATATION_AVG,0.7857,NaN,NaN,NaN,NaN
16,A_ORGANIZATION_TYPE,0.7858,NaN,NaN,NaN,NaN
17,A_FLAG_EMP_PHONE,0.7861,NaN,NaN,NaN,NaN
18,A_DEF_60_CNT_SOCIAL_CIRCLE,0.7864,NaN,NaN,NaN,NaN
19,A_NAME_INCOME_TYPE,0.7865,NaN,NaN,NaN,NaN
20,A_AMT_INCOME_TOTAL,0.7866,NaN,NaN,NaN,NaN
21,A_AMT_REQ_CREDIT_BUREAU_QRT,0.7867,NaN,NaN,NaN,NaN
22,A_DAYS_ID_PUBLISH,0.7868,NaN,NaN,NaN,NaN
23,A_AMT_REQ_CREDIT_BUREAU_DAY,0.7868,NaN,NaN,NaN,NaN
24,A_AMT_REQ_CREDIT_BUREAU_HOUR,0.7868,NaN,NaN,NaN,NaN
25,A_AMT_REQ_CREDIT_BUREAU_MON,0.7868,NaN,NaN,NaN,NaN
26,A_AMT_REQ_CREDIT_BUREAU_YEAR,0.7868,NaN,NaN,NaN,NaN
27,A_OBS_60_CNT_SOCIAL_CIRCLE,0.7868,NaN,NaN,NaN,NaN
28,A_OCCUPATION_TYPE,0.7868,NaN,NaN,NaN,NaN

In [53]:
a = np.intersect1d(log["keep"], dt["keep"])
a = np.intersect1d(a, rf["keep"])
a

array(['A_AMT_REQ_CREDIT_BUREAU_DAY', 'A_BASEMENTAREA_AVG',
       'A_DAYS_BIRTH', 'A_EXT_SOURCE_1', 'A_EXT_SOURCE_2',
       'A_EXT_SOURCE_3', 'A_LANDAREA_AVG'], dtype='<U29')

# Bureau

In [54]:
log = bureau_log
dt = bureau_dt
rf = bureau_rf

In [55]:
df = pd.DataFrame()
df = pd.concat([df,pd.DataFrame({"logistische Regression":log["keep"]})],axis=1)
df = pd.concat([df,pd.DataFrame({"AUC log. R.": [round(x,4) for x in log["auc"]]})],axis=1)
df = pd.concat([df,pd.DataFrame({"Entscheidungsbaum":dt["keep"]})],axis=1)
df = pd.concat([df,pd.DataFrame({"AUC DT": [round(x,4) for x in dt["auc"]]})],axis=1)
df = pd.concat([df,pd.DataFrame({"Random Forest":rf["keep"]})],axis=1)
df = pd.concat([df,pd.DataFrame({"AUC RF": [round(x,4) for x in rf["auc"]]})],axis=1)
df[0:10]

,logistische Regression,AUC log. R.,Entscheidungsbaum,AUC DT,Random Forest,AUC RF
0,B_Closed,0.5473,B_Closed,0.5478,B_Active,0.5604
1,B_Active,0.5917,B_Active,0.5974,B_Closed,0.5983
2,B_CREDIT_DAY_OVERDUE,0.5921,B_AMT_CREDIT_SUM,0.5988,B_AMT_CREDIT_SUM,0.6049
3,B_AMT_CREDIT_SUM_OVERDUE,0.5921,B_DAYS_CREDIT_ENDDATE,0.5992,B_AMT_CREDIT_SUM_DEBT,0.6123
4,B_DAYS_CREDIT_ENDDATE,0.5923,B_AMT_CREDIT_SUM_DEBT,0.5995,B_DAYS_CREDIT_ENDDATE,0.6125
5,B_AMT_ANNUITY,0.5926,CNT_BURAEU,0.5996,B_AMT_CREDIT_SUM_OVERDUE,0.6125
6,NaN,NaN,NaN,NaN,B_AMT_ANNUITY,0.6125

In [56]:
df

,logistische Regression,AUC log. R.,Entscheidungsbaum,AUC DT,Random Forest,AUC RF
0,B_Closed,0.5473,B_Closed,0.5478,B_Active,0.5604
1,B_Active,0.5917,B_Active,0.5974,B_Closed,0.5983
2,B_CREDIT_DAY_OVERDUE,0.5921,B_AMT_CREDIT_SUM,0.5988,B_AMT_CREDIT_SUM,0.6049
3,B_AMT_CREDIT_SUM_OVERDUE,0.5921,B_DAYS_CREDIT_ENDDATE,0.5992,B_AMT_CREDIT_SUM_DEBT,0.6123
4,B_DAYS_CREDIT_ENDDATE,0.5923,B_AMT_CREDIT_SUM_DEBT,0.5995,B_DAYS_CREDIT_ENDDATE,0.6125
5,B_AMT_ANNUITY,0.5926,CNT_BURAEU,0.5996,B_AMT_CREDIT_SUM_OVERDUE,0.6125
6,NaN,NaN,NaN,NaN,B_AMT_ANNUITY,0.6125

In [57]:
a = np.intersect1d(log["keep"], dt["keep"])
a = np.intersect1d(a, rf["keep"])
a

array(['B_Active', 'B_Closed', 'B_DAYS_CREDIT_ENDDATE'], dtype='<U24')

# PA_POS

In [58]:
log = pa_pos_log
dt = pa_pos_dt
rf = pa_pos_rf

In [59]:
df = pd.DataFrame()
df = pd.concat([df,pd.DataFrame({"logistische Regression":log["keep"]})],axis=1)
df = pd.concat([df,pd.DataFrame({"AUC log. R.": [round(x,4) for x in log["auc"]]})],axis=1)
df = pd.concat([df,pd.DataFrame({"Entscheidungsbaum":dt["keep"]})],axis=1)
df = pd.concat([df,pd.DataFrame({"AUC DT": [round(x,4) for x in dt["auc"]]})],axis=1)
df = pd.concat([df,pd.DataFrame({"Random Forest":rf["keep"]})],axis=1)
df = pd.concat([df,pd.DataFrame({"AUC RF": [round(x,4) for x in rf["auc"]]})],axis=1)
df[0:10]

,logistische Regression,AUC log. R.,Entscheidungsbaum,AUC DT,Random Forest,AUC RF
0,PA_AMT_CREDIT,0.5480,PA_CNT_NAME_CONTRACT_STATUS_Refused,0.5562,PA_CNT_NAME_CONTRACT_STATUS_Refused,0.5562
1,PA_AMT_ANNUITY,0.5639,PA_AMT_ANNUITY,0.5963,PA_AMT_ANNUITY,0.6003
2,PA_AMT_APPLICATION,0.5757,PA_POS_CNT_DPD,0.6009,PA_AMT_GOODS_PRICE,0.6041
3,PA_AMT_GOODS_PRICE,0.5757,PA_AMT_DOWN_PAYMENT,0.6075,PA_AMT_DOWN_PAYMENT,0.6122
4,PA_CNT_NAME_YIELD_GROUP_high,0.5979,PA_CNT_NAME_PRODUCT_TYPE_walk-in,0.6108,PA_CNT_NAME_PRODUCT_TYPE_walk-in,0.6182
5,PA_CNT_NAME_CONTRACT_STATUS_Refused,0.6150,PA_AMT_CREDIT,0.6115,PA_POS_CNT_DPD,0.6209
6,PA_CNT_CREDITS,0.6196,PA_CNT_NAME_YIELD_GROUP_high,0.6146,PA_AMT_CREDIT,0.6215
7,PA_POS_CNT_PAYMENTS_LEFT,0.6216,PA_CNT_NAME_CLIENT_TYPE_New,0.6164,PA_RATE_DOWN_PAYMENT,0.6215
8,PA_AMT_DOWN_PAYMENT,0.6244,PA_POS_CNT_PAYMENTS_LEFT,0.6164,PA_CNT_NAME_YIELD_GROUP_high,0.6267
9,PA_CNT_PRODUCT_COMBINATION_POS industry with interest,0.6249,PA_CNT_NAME_YIELD_GROUP_low_normal,0.6167,PA_POS_CNT_PAYMENTS_LEFT,0.6284

In [60]:
df

,logistische Regression,AUC log. R.,Entscheidungsbaum,AUC DT,Random Forest,AUC RF
0,PA_AMT_CREDIT,0.5480,PA_CNT_NAME_CONTRACT_STATUS_Refused,0.5562,PA_CNT_NAME_CONTRACT_STATUS_Refused,0.5562
1,PA_AMT_ANNUITY,0.5639,PA_AMT_ANNUITY,0.5963,PA_AMT_ANNUITY,0.6003
2,PA_AMT_APPLICATION,0.5757,PA_POS_CNT_DPD,0.6009,PA_AMT_GOODS_PRICE,0.6041
3,PA_AMT_GOODS_PRICE,0.5757,PA_AMT_DOWN_PAYMENT,0.6075,PA_AMT_DOWN_PAYMENT,0.6122
4,PA_CNT_NAME_YIELD_GROUP_high,0.5979,PA_CNT_NAME_PRODUCT_TYPE_walk-in,0.6108,PA_CNT_NAME_PRODUCT_TYPE_walk-in,0.6182
5,PA_CNT_NAME_CONTRACT_STATUS_Refused,0.6150,PA_AMT_CREDIT,0.6115,PA_POS_CNT_DPD,0.6209
6,PA_CNT_CREDITS,0.6196,PA_CNT_NAME_YIELD_GROUP_high,0.6146,PA_AMT_CREDIT,0.6215
7,PA_POS_CNT_PAYMENTS_LEFT,0.6216,PA_CNT_NAME_CLIENT_TYPE_New,0.6164,PA_RATE_DOWN_PAYMENT,0.6215
8,PA_AMT_DOWN_PAYMENT,0.6244,PA_POS_CNT_PAYMENTS_LEFT,0.6164,PA_CNT_NAME_YIELD_GROUP_high,0.6267
9,PA_CNT_PRODUCT_COMBINATION_POS industry with interest,0.6249,PA_CNT_NAME_YIELD_GROUP_low_normal,0.6167,PA_POS_CNT_PAYMENTS_LEFT,0.6284
10,PA_CNT_NAME_CONTRACT_TYPE_Revolving loans,0.6262,PA_CNT_NAME_CONTRACT_TYPE_Revolving loans,0.6167,PA_CNT_NAME_CLIENT_TYPE_New,0.6337
11,PA_CNT_NAME_CLIENT_TYPE_New,0.6310,PA_CNT_CREDITS,0.6168,PA_CNT_NAME_YIELD_GROUP_low_normal,0.6345
12,PA_RATE_DOWN_PAYMENT,0.6311,NaN,NaN,PA_CNT_NAME_CONTRACT_TYPE_Revolving loans,0.6347
13,PA_CNT_PRODUCT_COMBINATION_Cash X-Sell: low,0.6338,NaN,NaN,PA_CNT_CREDITS,0.6350
14,PA_POS_CNT_DPD,0.6348,NaN,NaN,PA_CNT_PRODUCT_COMBINATION_Cash X-Sell: low,0.6354
15,PA_CNT_NAME_CLIENT_TYPE_Refreshed,0.6352,NaN,NaN,PA_CNT_NAME_CLIENT_TYPE_Refreshed,0.6356
16,PA_CNT_NAME_YIELD_GROUP_low_normal,0.6352,NaN,NaN,PA_CNT_PRODUCT_COMBINATION_POS industry with interest,0.6361
17,PA_CNT_NAME_PORTFOLIO_Cards,0.6352,NaN,NaN,NaN,NaN
18,PA_CNT_NAME_PRODUCT_TYPE_walk-in,0.6353,NaN,NaN,NaN,NaN
19,PA_CNT_CODE_REJECT_REASON_HC,0.6354,NaN,NaN,NaN,NaN

In [61]:
a = np.intersect1d(log["keep"], dt["keep"])
a = np.intersect1d(a, rf["keep"])
a

array(['PA_AMT_ANNUITY', 'PA_AMT_CREDIT', 'PA_AMT_DOWN_PAYMENT',
       'PA_CNT_CREDITS', 'PA_CNT_NAME_CLIENT_TYPE_New',
       'PA_CNT_NAME_CONTRACT_STATUS_Refused',
       'PA_CNT_NAME_CONTRACT_TYPE_Revolving loans',
       'PA_CNT_NAME_PRODUCT_TYPE_walk-in', 'PA_CNT_NAME_YIELD_GROUP_high',
       'PA_CNT_NAME_YIELD_GROUP_low_normal', 'PA_POS_CNT_DPD',
       'PA_POS_CNT_PAYMENTS_LEFT'], dtype='<U53')

# PA_IP

In [62]:
log = pa_ip_log
dt = pa_ip_dt
rf = pa_ip_rf

In [63]:
df = pd.DataFrame()
df = pd.concat([df,pd.DataFrame({"logistische Regression":log["keep"]})],axis=1)
df = pd.concat([df,pd.DataFrame({"AUC log. R.": [round(x,4) for x in log["auc"]]})],axis=1)
df = pd.concat([df,pd.DataFrame({"Entscheidungsbaum":dt["keep"]})],axis=1)
df = pd.concat([df,pd.DataFrame({"AUC DT": [round(x,4) for x in dt["auc"]]})],axis=1)
df = pd.concat([df,pd.DataFrame({"Random Forest":rf["keep"]})],axis=1)
df = pd.concat([df,pd.DataFrame({"AUC RF": [round(x,4) for x in rf["auc"]]})],axis=1)
df[0:10]

,logistische Regression,AUC log. R.,Entscheidungsbaum,AUC DT,Random Forest,AUC RF
0,PA_AMT_ANNUITY,0.5437,PA_CNT_NAME_PRODUCT_TYPE_walk-in,0.5591,PA_CNT_NAME_PRODUCT_TYPE_walk-in,0.5590
1,PA_AMT_CREDIT,0.5488,PA_IP_DAYS_DIFF_30,0.5724,PA_IP_DAYS_DIFF_60,0.5760
2,PA_CNT_CREDITS,0.5666,PA_CNT_NAME_CONTRACT_STATUS_Refused,0.5776,PA_CNT_NAME_CONTRACT_STATUS_Refused,0.5834
3,PA_CNT_NAME_CONTRACT_STATUS_Refused,0.5898,PA_IP_DAYS_DIFF_180,0.5792,PA_IP_DAYS_DIFF_30,0.5901
4,PA_CNT_NAME_YIELD_GROUP_low_normal,0.6106,PA_AMT_ANNUITY,0.5898,PA_AMT_ANNUITY,0.6043
5,PA_CNT_NAME_CONTRACT_TYPE_Revolving loans,0.6118,PA_IP_DAYS_DIFF_60,0.5914,PA_IP_DAYS_DIFF_120,0.6070
6,PA_IP_DAYS_DIFF_60,0.6141,PA_IP_AMT_DIFF_180,0.5993,PA_IP_DAYS_DIFF_90,0.6088
7,PA_CNT_NAME_PORTFOLIO_Cards,0.6145,PA_IP_DAYS_DIFF_150,0.5994,PA_IP_DAYS_DIFF_180,0.6092
8,PA_CNT_NAME_CLIENT_TYPE_New,0.6219,PA_CNT_NAME_YIELD_GROUP_low_normal,0.6059,PA_AMT_CREDIT,0.6096
9,PA_CNT_PRODUCT_COMBINATION_POS industry with interest,0.6236,PA_RATE_DOWN_PAYMENT,0.6060,PA_IP_PAYMENT_180,0.6109

In [64]:
df

,logistische Regression,AUC log. R.,Entscheidungsbaum,AUC DT,Random Forest,AUC RF
0,PA_AMT_ANNUITY,0.5437,PA_CNT_NAME_PRODUCT_TYPE_walk-in,0.5591,PA_CNT_NAME_PRODUCT_TYPE_walk-in,0.5590
1,PA_AMT_CREDIT,0.5488,PA_IP_DAYS_DIFF_30,0.5724,PA_IP_DAYS_DIFF_60,0.5760
2,PA_CNT_CREDITS,0.5666,PA_CNT_NAME_CONTRACT_STATUS_Refused,0.5776,PA_CNT_NAME_CONTRACT_STATUS_Refused,0.5834
3,PA_CNT_NAME_CONTRACT_STATUS_Refused,0.5898,PA_IP_DAYS_DIFF_180,0.5792,PA_IP_DAYS_DIFF_30,0.5901
4,PA_CNT_NAME_YIELD_GROUP_low_normal,0.6106,PA_AMT_ANNUITY,0.5898,PA_AMT_ANNUITY,0.6043
5,PA_CNT_NAME_CONTRACT_TYPE_Revolving loans,0.6118,PA_IP_DAYS_DIFF_60,0.5914,PA_IP_DAYS_DIFF_120,0.6070
6,PA_IP_DAYS_DIFF_60,0.6141,PA_IP_AMT_DIFF_180,0.5993,PA_IP_DAYS_DIFF_90,0.6088
7,PA_CNT_NAME_PORTFOLIO_Cards,0.6145,PA_IP_DAYS_DIFF_150,0.5994,PA_IP_DAYS_DIFF_180,0.6092
8,PA_CNT_NAME_CLIENT_TYPE_New,0.6219,PA_CNT_NAME_YIELD_GROUP_low_normal,0.6059,PA_AMT_CREDIT,0.6096
9,PA_CNT_PRODUCT_COMBINATION_POS industry with interest,0.6236,PA_RATE_DOWN_PAYMENT,0.6060,PA_IP_PAYMENT_180,0.6109
10,PA_CNT_NAME_PRODUCT_TYPE_walk-in,0.6256,PA_IP_PAYMENT_60,0.6061,PA_AMT_APPLICATION,0.6120
11,PA_CNT_NAME_CLIENT_TYPE_Refreshed,0.6260,PA_IP_AMT_DIFF_120,0.6062,PA_IP_AMT_DIFF_60,0.6192
12,PA_AMT_APPLICATION,0.6268,PA_CNT_CODE_REJECT_REASON_HC,0.6063,PA_IP_AMT_DIFF_30,0.6196
13,PA_AMT_DOWN_PAYMENT,0.6278,PA_AMT_DOWN_PAYMENT,0.6064,PA_IP_DAYS_DIFF_150,0.6201
14,PA_CNT_PRODUCT_COMBINATION_Cash X-Sell: low,0.6283,PA_CNT_PRODUCT_COMBINATION_Card Street,0.6064,PA_CNT_NAME_YIELD_GROUP_low_normal,0.6261
15,PA_RATE_DOWN_PAYMENT,0.6283,PA_AMT_APPLICATION,0.6075,PA_CNT_PRODUCT_COMBINATION_Cash X-Sell: low,0.6265
16,PA_IP_DAYS_DIFF_180,0.6287,NaN,NaN,PA_IP_PAYMENT_60,0.6268
17,PA_IP_DAYS_DIFF_90,0.6288,NaN,NaN,PA_IP_AMT_DIFF_180,0.6275
18,PA_IP_PAYMENT_180,0.6290,NaN,NaN,PA_IP_AMT_DIFF_90,0.6276
19,PA_IP_DAYS_DIFF_150,0.6290,NaN,NaN,PA_CNT_NAME_CONTRACT_TYPE_Revolving loans,0.6282
20,PA_IP_PAYMENT_120,0.6290,NaN,NaN,PA_IP_AMT_DIFF_150,0.6287
21,PA_IP_PAYMENT_60,0.6293,NaN,NaN,PA_CNT_NAME_CLIENT_TYPE_New,0.6330
22,PA_IP_PAYMENT_150,0.6294,NaN,NaN,PA_CNT_NAME_YIELD_GROUP_high,0.6330
23,PA_IP_DAYS_DIFF_30,0.6294,NaN,NaN,PA_CNT_NAME_PORTFOLIO_Cards,0.6333
24,NaN,NaN,NaN,NaN,PA_CNT_NAME_CLIENT_TYPE_Refreshed,0.6345
25,NaN,NaN,NaN,NaN,PA_CNT_PRODUCT_COMBINATION_POS industry with interest,0.6354
26,NaN,NaN,NaN,NaN,PA_RATE_DOWN_PAYMENT,0.6362

In [65]:
a = np.intersect1d(log["keep"], dt["keep"])
a = np.intersect1d(a, rf["keep"])
a

array(['PA_AMT_ANNUITY', 'PA_AMT_APPLICATION',
       'PA_CNT_NAME_CONTRACT_STATUS_Refused',
       'PA_CNT_NAME_PRODUCT_TYPE_walk-in',
       'PA_CNT_NAME_YIELD_GROUP_low_normal', 'PA_IP_DAYS_DIFF_150',
       'PA_IP_DAYS_DIFF_180', 'PA_IP_DAYS_DIFF_30', 'PA_IP_DAYS_DIFF_60',
       'PA_IP_PAYMENT_60', 'PA_RATE_DOWN_PAYMENT'], dtype='<U53')

# PA_CC

In [66]:
log = pa_cc_log
dt = pa_cc_dt
rf = pa_cc_rf

In [67]:
df = pd.DataFrame()
df = pd.concat([df,pd.DataFrame({"logistische Regression":log["keep"]})],axis=1)
df = pd.concat([df,pd.DataFrame({"AUC log. R.": [round(x,4) for x in log["auc"]]})],axis=1)
df = pd.concat([df,pd.DataFrame({"Entscheidungsbaum":dt["keep"]})],axis=1)
df = pd.concat([df,pd.DataFrame({"AUC DT": [round(x,4) for x in dt["auc"]]})],axis=1)
df = pd.concat([df,pd.DataFrame({"Random Forest":rf["keep"]})],axis=1)
df = pd.concat([df,pd.DataFrame({"AUC RF": [round(x,4) for x in rf["auc"]]})],axis=1)
df[0:10]

,logistische Regression,AUC log. R.,Entscheidungsbaum,AUC DT,Random Forest,AUC RF
0,PA_AMT_ANNUITY,0.5285,PA_CC_BALANCE_60,0.6029,PA_CC_BALANCE_60,0.6083
1,PA_AMT_CREDIT,0.5295,PA_CNT_NAME_PRODUCT_TYPE_walk-in,0.6264,PA_CC_BALANCE_30,0.6129
2,PA_CC_DPD_30,0.5310,PA_CC_BALANCE_90,0.6284,PA_CC_BALANCE_90,0.6130
3,PA_CC_BALANCE_180,0.5419,PA_CNT_NAME_CONTRACT_STATUS_Refused,0.6301,PA_CC_BALANCE_180,0.6130
4,PA_CNT_NAME_CONTRACT_STATUS_Refused,0.5763,PA_CC_PAYMENT_180,0.6315,PA_CC_BALANCE_120,0.6138
5,PA_CNT_NAME_YIELD_GROUP_low_normal,0.5972,PA_CNT_PRODUCT_COMBINATION_Cash X-Sell: low,0.6328,PA_CNT_NAME_PRODUCT_TYPE_walk-in,0.6345
6,PA_CNT_NAME_CLIENT_TYPE_New,0.6090,PA_CC_BALANCE_150,0.6332,PA_CC_PAYMENT_60,0.6377
7,PA_CC_BALANCE_60,0.6122,PA_CC_DPD_30,0.6332,PA_CC_PAYMENT_180,0.6379
8,PA_CNT_NAME_PRODUCT_TYPE_walk-in,0.6150,PA_CC_DPD_90,0.6335,PA_CC_PAYMENT_120,0.6382
9,PA_CNT_NAME_PORTFOLIO_Cards,0.6158,PA_CC_PAYMENT_30,0.6336,PA_CNT_NAME_CONTRACT_STATUS_Refused,0.6415

In [68]:
df

,logistische Regression,AUC log. R.,Entscheidungsbaum,AUC DT,Random Forest,AUC RF
0,PA_AMT_ANNUITY,0.5285,PA_CC_BALANCE_60,0.6029,PA_CC_BALANCE_60,0.6083
1,PA_AMT_CREDIT,0.5295,PA_CNT_NAME_PRODUCT_TYPE_walk-in,0.6264,PA_CC_BALANCE_30,0.6129
2,PA_CC_DPD_30,0.5310,PA_CC_BALANCE_90,0.6284,PA_CC_BALANCE_90,0.6130
3,PA_CC_BALANCE_180,0.5419,PA_CNT_NAME_CONTRACT_STATUS_Refused,0.6301,PA_CC_BALANCE_180,0.6130
4,PA_CNT_NAME_CONTRACT_STATUS_Refused,0.5763,PA_CC_PAYMENT_180,0.6315,PA_CC_BALANCE_120,0.6138
5,PA_CNT_NAME_YIELD_GROUP_low_normal,0.5972,PA_CNT_PRODUCT_COMBINATION_Cash X-Sell: low,0.6328,PA_CNT_NAME_PRODUCT_TYPE_walk-in,0.6345
6,PA_CNT_NAME_CLIENT_TYPE_New,0.6090,PA_CC_BALANCE_150,0.6332,PA_CC_PAYMENT_60,0.6377
7,PA_CC_BALANCE_60,0.6122,PA_CC_DPD_30,0.6332,PA_CC_PAYMENT_180,0.6379
8,PA_CNT_NAME_PRODUCT_TYPE_walk-in,0.6150,PA_CC_DPD_90,0.6335,PA_CC_PAYMENT_120,0.6382
9,PA_CNT_NAME_PORTFOLIO_Cards,0.6158,PA_CC_PAYMENT_30,0.6336,PA_CNT_NAME_CONTRACT_STATUS_Refused,0.6415
10,PA_CNT_NAME_CONTRACT_TYPE_Revolving loans,0.6175,PA_CC_DPD_180,0.6337,PA_AMT_CREDIT,0.6434
11,PA_CNT_PRODUCT_COMBINATION_POS industry with interest,0.6201,PA_CC_DPD_120,0.6344,PA_AMT_APPLICATION,0.6458
12,PA_CC_DPD_60,0.6201,PA_CNT_CODE_REJECT_REASON_HC,0.6344,PA_AMT_GOODS_PRICE,0.6463
13,PA_CC_PAYMENT_60,0.6207,PA_CNT_CREDITS,0.6346,PA_CNT_CODE_REJECT_REASON_HC,0.6464
14,PA_CNT_NAME_CLIENT_TYPE_Refreshed,0.6209,NaN,NaN,PA_CNT_NAME_YIELD_GROUP_high,0.6468
15,PA_CC_DPD_180,0.6211,NaN,NaN,PA_CNT_NAME_CLIENT_TYPE_New,0.6483
16,PA_CC_PAYMENT_90,0.6216,NaN,NaN,PA_CNT_PRODUCT_COMBINATION_Cash X-Sell: low,0.6494
17,PA_CNT_CODE_REJECT_REASON_HC,0.6217,NaN,NaN,PA_CNT_NAME_YIELD_GROUP_low_normal,0.6500
18,PA_CC_BALANCE_30,0.6219,NaN,NaN,PA_CNT_NAME_CLIENT_TYPE_Refreshed,0.6504
19,PA_CC_PAYMENT_150,0.6221,NaN,NaN,PA_CNT_PRODUCT_COMBINATION_POS industry with interest,0.6505
20,PA_CC_BALANCE_150,0.6224,NaN,NaN,PA_CC_DPD_180,0.6509
21,PA_CNT_NAME_YIELD_GROUP_high,0.6224,NaN,NaN,NaN,NaN

In [69]:
a = np.intersect1d(log["keep"], dt["keep"])
a = np.intersect1d(a, rf["keep"])
a

array(['PA_CC_BALANCE_60', 'PA_CC_DPD_180',
       'PA_CNT_CODE_REJECT_REASON_HC',
       'PA_CNT_NAME_CONTRACT_STATUS_Refused',
       'PA_CNT_NAME_PRODUCT_TYPE_walk-in'], dtype='<U53')